[package]
name = "satscript-validator-runtime-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.9"
hex = "0.4"
rlp = "0.5.2"
cpython = "0.5.2"

